#!/system/bin/sh

BUSYBOX=/data/data/com.huntmix.pw0boom/cache/busybox
if [ -z "$BUSYBOX" ]; then
    echo "[-] No busybox"
    exit 1
fi

function show_usage() {
    echo "[!] Usage: sh changemac [interface_name] [mac_address]"
}

if [ -z "$1" -o -z "$2" ]; then
    show_usage
    exit 1
fi

if echo "$2" | $BUSYBOX grep "[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}:[0-9a-f]{2}"; then
    show_usage
    exit 1
fi

IFACE=$1
MACADDRESS=$2
echo "[!] Changing Mac address for $1 to $2. This can take a while..."

ANDROID_VER=$(getprop ro.build.version.release)

if [ ${ANDROID_VER//\.*} -ge 10 ]; then
    svc wifi disable
    svc wifi enable

    sleep 5
    $BUSYBOX ip link set dev $IFACE down
    CURRENT_TIME=$(date +%s)
    while true; do
        if $BUSYBOX ip link set dev $IFACE address $MACADDRESS 2>/dev/null; then
            svc wifi enable
            echo "[+] Completed."
            break
        else
            if [ $(($(date +%s) - $CURRENT_TIME)) -lt 10 ]; then
                continue
            else
                exit 1
            fi
        fi
    done
    sleep 1
    $BUSYBOX ip link set dev $IFACE up
    exit 0
else
    settings put global airplane_mode_on 1
    am broadcast -a android.intent.action.AIRPLANE_MODE --ez state true
    sleep 5
    settings put global airplane_mode_on 0
    am broadcast -a android.intent.action.AIRPLANE_MODE --ez state false
    CURRENT_TIME=$(date +%s)
    while true; do
        if $BUSYBOX ip link set dev $IFACE address $MACADDRESS 2>/dev/null; then
            svc wifi enable
            echo "[+] Completed."
            exit 0
        else
            if [ $(($(date +%s) - $CURRENT_TIME)) -lt 10 ]; then
                continue
            else
                exit 1
            fi
        fi
    done
fi